spring:
  application:
    name: file-transfer-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

app:
  cors:
    allowed-origin: http://localhost:4200
  storage:
    path: ${java.io.tmpdir}/file-transfer
